<script src="<?= PATH ?>/Public/js/theme/bootstrap.min.js"></script>
<script src="<?= PATH ?>/Public/js/theme/jquery.nice-select.min.js"></script>
<script src="<?= PATH ?>/Public/js/theme/jquery-ui.min.js"></script>
<script src="<?= PATH ?>/Public/js/theme/jquery.nicescroll.min.js"></script>
<script src="<?= PATH ?>/Public/js/theme/jquery.barfiller.js"></script>
<script src="<?= PATH ?>/Public/js/theme/jquery.magnific-popup.min.js"></script>
<script src="<?= PATH ?>/Public/js/theme/jquery.slicknav.js"></script>
<script src="<?= PATH ?>/Public/js/theme/owl.carousel.min.js"></script>
<script src="<?= PATH ?>/Public/js/theme/main.js"></script>
<script src="<?= PATH ?>/Public/js/jquery.rateyo.min.js"></script>
